
CREATE TABLE ADDRESS_CODE
(
  ADDRESS         VARCHAR NULL     COMMENT '주소',
  ADDRESS_CODE_ID VARCHAR NOT NULL,
  PRIMARY KEY (ADDRESS_CODE_ID)
) COMMENT '주소 코드';

CREATE TABLE GENDER_CODE
(
  GENDER      VARCHAR NULL     COMMENT '성별',
  GENDER_CODE VARCHAR NOT NULL,
  PRIMARY KEY (GENDER_CODE)
) COMMENT '성별코드';

CREATE TABLE HOBBY_CODE
(
  HOBBY         VARCHAR NULL     COMMENT '취미명',
  HOBBY_CODE_ID         NOT NULL,
  PRIMARY KEY (HOBBY_CODE_ID)
) COMMENT '취미 코드';

CREATE TABLE MEMBERS
(
  NAME            VARCHAR NULL     COMMENT '이름',
  AGE             INTEGER NULL     COMMENT '나이',
  ADDRESS         VARCHAR NULL     COMMENT '주소',
  TELEPHONE       VARCHAR NULL     COMMENT '전화번호',
  MEMBERS_ID      VARCHAR NOT NULL COMMENT '유니크 ID',
  GENDER_CODE     VARCHAR NOT NULL,
  ADDRESS_CODE_ID VARCHAR NOT NULL,
  PRIMARY KEY (MEMBERS_ID)
) COMMENT '회원정보';

CREATE TABLE MEMBERS_HOBBY
(
  MEMBERS_ID    VARCHAR NOT NULL COMMENT '유니크 ID',
  HOBBY_CODE_ID         NOT NULL
) COMMENT '회원_취미';

CREATE TABLE MEMBERS_LOGIN
(
  EMAIL            VARCHAR NULL     COMMENT '이메일',
  MEMBERS_LOGIN_ID VARCHAR NOT NULL COMMENT '회원 로그인 id',
  MEMBERS_ID       VARCHAR NOT NULL COMMENT '유니크 ID',
  PRIMARY KEY (MEMBERS_LOGIN_ID)
) COMMENT '회원 로그인';

ALTER TABLE MEMBERS_HOBBY
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBERS_HOBBY
    FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS (MEMBERS_ID);

ALTER TABLE MEMBERS_LOGIN
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBERS_LOGIN
    FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS (MEMBERS_ID);

ALTER TABLE MEMBERS_HOBBY
  ADD CONSTRAINT FK_HOBBY_CODE_TO_MEMBERS_HOBBY
    FOREIGN KEY (HOBBY_CODE_ID)
    REFERENCES HOBBY_CODE (HOBBY_CODE_ID);

ALTER TABLE MEMBERS
  ADD CONSTRAINT FK_GENDER_CODE_TO_MEMBERS
    FOREIGN KEY (GENDER_CODE)
    REFERENCES GENDER_CODE (GENDER_CODE);

ALTER TABLE MEMBERS
  ADD CONSTRAINT FK_ADDRESS_CODE_TO_MEMBERS
    FOREIGN KEY (ADDRESS_CODE_ID)
    REFERENCES ADDRESS_CODE (ADDRESS_CODE_ID);
